### ISSUE TITLE
version 3.5.0   Deoldify not working 

### ISSUE THREAD

**Issue by TechHalloman** [dan64/vs-deoldify#2]
latest v3.5 DDColor working Deoldify   Options gray marked not working .

**Comment by dan64** [comment]
Are you using the last version of [Hybrid 2024.05.05.1](https://www.selur.de/sites/default/files/hybrid_downloads/Hybrid_2024.05.05.1_SETUP.exe) ?

**Comment by TechHalloman** [comment]
yes. two latest verstions used (Hybrid and plugins). ddcolour working. but deoldify not respond  and all options gay colured

**Comment by dan64** [comment]
This version is using the Presets to simplify its usage. In this case you are using the Preset "fast" and all the filter parameters are selected automatically. To enable full editing of filter parameters you need to select the Preset "custom".

**Comment by TechHalloman** [comment]
ok i will try

**Comment by dan64** [comment]
It is not possible to define Presets working for everyone. In any case using the "custom" preset is is possible to manually change all the filter parameters. I consider the issue closed.
